### ISSUE TITLE
请教一下羡辙，如何制作chrome插件

### ISSUE THREAD

**Issue by Angus-Liu** [Ovilia/readfree-chrome-extension#10]
请教一下羡辙，如何制作chrome插件？有哪些参考资料呢？因为我是学后端开发的，前端学的比较少，所以想请教一下插件开发方面的学习资料。目前想做的插件和readfree-chrome-extension功能上有相似的地方，所以请教一下，万分感谢！

**Comment by Ovilia** [comment]
其实这个插件有点越写越乱了，我也懒得重构，还是看官方教程吧：https://developer.chrome.com/extensions/getstarted

**Comment by Angus-Liu** [comment]
好的，谢谢！
