### ISSUE TITLE
ReadFree选择豆瓣登录后，跳出502页面

### ISSUE THREAD

**Issue by visaia** [Ovilia/readfree-chrome-extension#12]
![image](https://user-images.githubusercontent.com/26156418/57215110-8e492980-701e-11e9-821d-51657ad75b41.png)
ReadFree选择豆瓣登录后，跳出502页面

**Comment by Ovilia** [comment]
这个项目只和 Chrome 插件相关，ReadFree 网站的问题请在这里反馈：https://readfree.me/contact/
