### ISSUE TITLE
插件适配

### ISSUE THREAD

**Issue by jingchenyanan** [Ovilia/readfree-chrome-extension#13]
谷歌浏览器新的插件兼容性不是很好，可以做一下适配吗？

**Comment by Ovilia** [comment]
具体是怎么不兼容？有什么问题？

**Comment by jingchenyanan** [comment]
实际上我打开豆瓣读书模块后刚开始是没有显示有readfree的标志的，后来刷新几次后才会有一些书籍有这个标志

Ovilia <notifications@github.com> 于2019年5月10日周五 上午10:35写道：

**Comment by Ovilia** [comment]
这可能是网络问题或者是 ReadFree 网站请求速度问题，和插件没有关系
