### ISSUE TITLE
插件疑似不工作

### ISSUE THREAD

**Issue by changlan** [Ovilia/readfree-chrome-extension#2]
豆瓣页面上的 Readfree 链接不显示了，我的 Chrome 版本是 50.0.2661.86 (64-bit)，Mac OS X 10.11。

**Comment by Ovilia** [comment]
@changlan 的确是的，这个问题是由于豆瓣全站换了 HTTPS，需要 ReadFree 的网站也换 HTTPS 才行。我跟站长联系过了，他最近比较忙，等他搞定后我会更新的。
