### ISSUE TITLE
readfree.me 进不去

### ISSUE THREAD

**Issue by lubyxu** [Ovilia/readfree-chrome-extension#6]
请问下 http://readfree.me/accounts/login/这个页面，我用豆瓣账号打死也进不去。。
![image](https://user-images.githubusercontent.com/8433782/44901182-42304180-ad39-11e8-8d93-75d01fcf6c1c.png)
求帮助。wenli上神~~~~~

**Comment by Ovilia** [comment]
这个项目只是个插件，跟 ReadFree 本身没有关系，我也没法维护 ReadFree 本身的问题~
建议到 http://forum.readfree.me/ 提问吧~
