### ISSUE TITLE
readfree 的 search 接口无法获得数据

### ISSUE THREAD

**Issue by AuTa** [Ovilia/readfree-chrome-extension#8]
https://github.com/Ovilia/readfree-chrome-extension/blob/061b55d14978f4f08d3bfec4f4d87078a7c01ee6/src/show.js#L19

控制台显示：
show.js:formatted:1253 

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://readfree.me/search/?q=6709783&fmt=json with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by AuTa** [comment]
这篇文章最开头说明，似乎只能在背景页中跨域请求了。
[Changes to Cross-Origin Requests in Chrome Extension Content Scripts](http://dev.chromium.org/Home/chromium-security/extension-content-script-fetches)

**Comment by Ovilia** [comment]
我这边 72 版本没有报这个错。
事实上一起我的确是用 background 的方式请求的，后来发现直接请求并不会报错就直接请求了……
我回头再研究下~谢谢！

**Comment by Ovilia** [comment]
> In most cases, the blocked response should not affect the web page's behavior and the CORB error message can be safely ignored.
> https://www.chromium.org/Home/chromium-security/corb-for-developers

在你的环境中有遇到因此引起的问题吗？如果没有的话，我不准备改动这块的逻辑。当然，非常感谢你的 PR。

**Comment by AuTa** [comment]
> > In most cases, the blocked response should not affect the web page's behavior and the CORB error message can be safely ignored.
> > [chromium.org/Home/chromium-security/corb-for-developers](https://www.chromium.org/Home/chromium-security/corb-for-developers)
> 
> 在你的环境中有遇到因此引起的问题吗？如果没有的话，我不准备改动这块的逻辑。当然，非常感谢你的 PR。

我的版本是这个
版本 74.0.3717.0（正式版本）dev （64 位）

官方说法是：
> This change starts in Chrome 73 (version 73.0.3666.0), which will reach Beta channel around February 7 and Stable channel around March 12.  

我大概二月份的时候就没看到 readfree 的提示了。

**Comment by Ovilia** [comment]
> 我大概二月份的时候就没看到 readfree 的提示了。

这个的意思是二月份开始没问题了？

如果目前只是 dev 版有这个问题的话，我还是会等到正式版也有这个问题的时候再选择修复。

**Comment by 42captain** [comment]
豆瓣页面看不到展示了，卸载重装后也不显示

**Comment by Ovilia** [comment]
似乎是因为这个原因，暂时还没修复……

**Comment by Ovilia** [comment]
https://github.com/Ovilia/readfree-chrome-extension/commit/75d8e9297ede6217f8975f67d10c8b074c7e623f
已修复，等 2.9.6 版本上线就修复了。

**Comment by 42captain** [comment]
正常使用了，感谢
